### ISSUE TITLE
yii2组件的配置数组，能否引用到tars-web端的远程配置的值

### ISSUE THREAD

**Issue by wcb0107** [luoxiaojun1992/yii2-tars#5]
/src/config/web.php中的components组件配置，能否使用tars远端的配置文件中的值进行配置。目前看到了已将远端名为tars的文件配置合并入Yii::$app->params数组内，但是合并时，Yii::$app->component都已经完成初始化了。请问有没有好的办法？

**Comment by luoxiaojun1992** [comment]
yii2好像不支持动态修改配置。
假设需要实现的话，只能通过文件替换。

有如下问题
1. json不能完全替代php array，只能做部分替换，要对文件内容做复杂的对比，可能会影响性能
2. yii2没有提供动态修改配置的方法，直接替换文件可能会有权限、安全性等问题
3. 拉取tars-config配置需要服务启动的配置，只能在server启动后通过App::getTarsConfig()获取，server启动前后的配置会有不一致，而且多个进程同时拉取配置，替换文件也会影响性能或者产生其他问题
4. 目前tars-config配置只能在启动时拉取，并不能动态更新，完全用tars-config的配置没有意义，完全可以通过运维部署阶段替换配置文件，实现配置的下发
5. 需求不通用

如果确有需求，建议自己定制，谢谢
