### ISSUE TITLE
test for new release

### ISSUE THREAD

**Issue by luoxiaojun1992** [luoxiaojun1992/yii2-tars#6]

**Comment by wcb0107** [comment]
在控制器中return;/return null;/不return时，Response返回throw new \Exception("Invalid yii2 response object"); 是否考虑允许上面三种返回。

**Comment by luoxiaojun1992** [comment]
> 在控制器中return;/return null;/不return时，Response返回throw new \Exception("Invalid yii2 response object"); 是否考虑允许上面三种返回。

控制器应该返回有意义的内容，或者空字符串
